version: "3.8"

sservices:
  app:
    build: .
    container_name: totp-auth-yashu
    ports:
      - "8080:8080"
    volumes:
      - seed-data:/data
      - cron-output:/cron
      # mount local key files read-only (helpful for local dev)
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro
    environment:
      - TZ=UTC
    restart: unless-stopped

volumes:
  seed-data:
  cron-output:

